### ISSUE TITLE
jdcal dependency not specified in conda-forge release

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-cds#14] opened 2020-10-14 14:48 UTC
When installing xcube-cds via conda-forge I have to manually add 
`$ conda install -c conda-forge jdcal ` afterwards in order to make xcube-cds work. This should not happen :)

**Comment by pont-us** [comment] 2020-11-03 09:02
As far as I can tell, this is an xcube problem rather than an xcube-cds problem: xcube-cds doesn't have any direct dependency on jdcal, but it does use `xcube.core.normalize`, which *does* require jdcal. However, the latest (0.5.1) xcube conda-forge release doesn't specify jdcal in the dependencies. So what needs to happen is:

1. Add jdcal to dependencies in [xcube's conda-forge meta.yaml file](https://github.com/conda-forge/xcube-feedstock/blob/master/recipe/meta.yaml) (more generally: ensure that all xcube's dependencies are listed in both its `environment.yml` and `meta.yaml` files).

2. Make a new conda-forge release of xcube with the corrected dependencies.

3. Bump xcube-cds's xcube dependency from 0.5.0 to 0.5.2 and make a new xcube-cds conda-forge release. (Probably not strictly necessary, since conda and mamba will tend to prefer the latest available xcube version, but should be done to be entirely safe and corrrect :) ).

**Comment by pont-us** [comment] 2020-11-03 10:55
I forgot: I already have an [xcube-feedstock pull request in progress](https://github.com/conda-forge/xcube-feedstock/pull/11) for jdcal and a few other missing xcube conda-forge dependencies. This will be a 0.5.1build1 release rather than 0.5.2, but as soon as it's out I can make a new xcube-cds release (both GitHub and conda-forge) to enforce the dependency on the new xcube version. Currently the PR is waiting on input from Helge.

**Comment by pont-us** [comment] 2020-11-12 10:41
Update: xcube 0.5.1build1 is now out, but since the upcoming v0.6.0 release of both xcube and xcube-cds will fix the problem anyway, I'm not convinced that it's worth the time and effort to make a new xcube-cds 0.5.1build1 release now just to bump the version of the xcube dependency.

**Comment by pont-us** [comment] 2020-12-02 13:38
xcube 0.6.0 and xcube-cds 0.6.0 have now been released. I have made a clean install of the xcube-cds 0.6.0 package from conda-forge and confirmed that jdcal is automatically installed as a dependency, so I'm closing this issue as fixed.

**Closed by pont-us** 2020-12-02 13:38 UTC
