### ISSUE TITLE
different result for variable names when using store.get_open_data_params_schema(data_id) or store.describe_data(data_id)

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-cds#15] opened 2020-10-19 09:14 UTC
When I take a look at the variable names of a dataset via the xcube-cds plugin, I get different results when using `store.get_open_data_params_schema(data_id)` and 
`store.describe_data(data_id)`

To reproduce: 
``` 
from xcube.core.store import new_data_store

store = new_data_store('cds')
data_id = 'reanalysis-era5-single-levels-monthly-means:monthly_averaged_reanalysis'

store.get_open_data_params_schema(data_id)
```
![image](https://user-images.githubusercontent.com/23457217/96425050-ddc3eb00-11fb-11eb-9db4-d3528958f0fb.png)
```
store.describe_data(data_id)
```
![image](https://user-images.githubusercontent.com/23457217/96425218-15329780-11fc-11eb-8aab-ff64254485f6.png)

Is this intentional? When I compare both ways of accessing data variables with xcube-sh plugin, the result is the same for both manners.

**Comment by pont-us** [comment] 2020-11-03 15:42
The CDS API doesn't have unified variable names between the request and the result -- in some cases, e.g. in the soil moisture data set, there isn't even a one-to-one mapping between the two sets of variables. the CDS store plugin generally tries to provide a thin interface to the CDS API (i.e. manipulates the requests and results as little as possible). Of course it would be possible to expand the scope of the plugin to rename variables and unify the two schemes, but that's quite a lot of implementation and maintenance effort. We could discuss whether this ought to be a design goal for the plugin, but for now I'll close this issue as "by design".

**Comment by AliceBalfanz** [comment] 2020-12-09 13:06
Reopening, because the behavior also affects the xcube generator and is really user-unfriendly. 
operational (old) xcube generator version (xcube Generation  • UI v1.0.8 • API v1.0.12)

![image](https://user-images.githubusercontent.com/23457217/101633227-432b9f80-3a27-11eb-9bd1-2bc1999b7fb3.png)

new version in stage xcube generator (xcube Generation  • UI v1.1.0-dev.3 • API v1.0.13.dev1)
![image](https://user-images.githubusercontent.com/23457217/101633358-648c8b80-3a27-11eb-971f-2033a6fc0419.png)

Furthermore it differs to the other stores, where cube generation request can be build by using the data_var.name provided within the `store.describe_data(data_id)`

**Comment by pont-us** [comment] 2020-12-09 14:14
The new generator version simply looks incorrect to me: it's taking the variable names from `describe_data`, not from `get_open_data_params_schema`. I expect that this will also cause the request to fail. `describe_data` describes the structure of the returned data, not the structure of the request.

**Comment by pont-us** [comment] 2021-02-12 14:04
After discussion today: still no clear resolution on how we should proceed with this, so I'm leaving the bug open but not actively working on it. Obviously we'll have to come to a decision before the next gen UI release, since this bug almost certainly breaks generation of CDS data cubes in the UI.

**Comment by pont-us** [comment] 2023-08-08 10:46
Closing as duplicate of #72 . We're keeping the newer issue open in order to exclude the now-irrelevant discussion of the generator.

**Comment by pont-us** [comment] 2023-08-08 10:48
Closing as duplicate of #72 . We're keeping the newer issue open in order to exclude the now-irrelevant discussion of the generator.

**Closed** 2023-08-08 10:48 UTC
Labels: bug, duplicate, question
